sudo: required

language: node_js

services:
  - docker

node_js:
  - "node"

before_install:
- docker pull pinholecamera/backend
- docker run --rm -d -p 5000:5000 pinholecamera/backend
- docker ps -a

install:
  - npm install

script:
  - npm run test
  - npm run lint

notifications:
  email: false
