export interface ISpecs {
  id: number;
  pinhole_diameter: number;
  focal_length: number;
  image_width: number;
  distortion: number;
  pinhole_to_image_angle: number;
  created_at: string;
  updated_at: string;
}

export interface ICameraState {
  specs: ISpecs[];
  selectCamera: number;
  selectPinholeDiameter: number;
}

export const enum CameraActionTypes {
  GET_CAMERAS = 'GET_CAMERAS',
  GET_CAMERAS_PENDING = 'GET_CAMERAS_PENDING',
  GET_CAMERAS_FULFILLED = 'GET_CAMERAS_FULFILLED',
  GET_CAMERAS_REJECTED = 'GET_CAMERAS_REJECTED',
  SHOW_CAMERA = 'SHOW_CAMERA',
  SHOW_CAMERA_PENDING = 'SHOW_CAMERA_PENDING',
  SHOW_CAMERA_FULFILLED = 'SHOW_CAMERA_FULFILLED',
  SHOW_CAMERA_REJECTED = 'SHOW_CAMERA_REJECTED',
  CREATE_CAMERA = 'CREATE_CAMERA',
  CREATE_CAMERA_PENDING = 'CREATE_CAMERA_PENDING',
  CREATE_CAMERA_FULFILLED = 'CREATE_CAMERA_FULFILLED',
  CREATE_CAMERA_REJECTED = 'CREATE_CAMERA_REJECTED',
  SELECT_CAMERA = 'SELECT_CAMERA',
  SELECT_CAMERA_PENDING = 'SELECT_CAMERA_PENDING',
  SELECT_CAMERA_FULFILLED = 'SELECT_CAMERA_FULFILLED',
  SELECT_CAMERA_REJECTED = 'SELECT_CAMERA_REJECTED',
  SELECT_PINHOLE_DIAMETER = 'SELECT_PINHOLE_DIAMETER',
  SELECT_PINHOLE_DIAMETER_PENDING = 'SELECT_PINHOLE_DIAMETER_PENDING',
  SELECT_PINHOLE_DIAMETER_FULFILLED = 'SELECT_PINHOLE_DIAMETER_FULFILLED',
  SELECT_PINHOLE_DIAMETER_REJECTED = 'SELECT_PINHOLE_DIAMETER_REJECTED',
}
